---
- name: parse the item values
  ansible.builtin.set_fact:
    nc_app_name: "{{ item }}"

- name: "Disable Nextcloud Apps"
  block:
    - name: "[ App {{ nc_app_name }} ] - disable the application."
      become_user: "{{ nextcloud_websrv_user }}"
      become_flags: "{{ ansible_become_flags | default(omit) }}"
      become: true
      ansible.builtin.command: php occ app:disable "{{ nc_app_name }}"
      args:
        chdir: "{{ nextcloud_webroot }}"
      when: nc_app_name is not none
  when: nc_app_name is string
